---
title: A title
subtitle: A subtitle
format: tum-revealjs
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Pratik Nayak
    orcid: 0000-0002-7961-1159
    email: pratik.nayak@tum.de
    affiliations: Technical University of Munich
date: last-modified
---

## Example slide

::: {.sectionhead}
Example [Additional Code Summary]{style="opacity:0.25"}
:::

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

::: {.sectionhead}
[Example]{style="opacity:0.25"} Additional [Code Summary]{style="opacity:0.25"}
:::

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Code views

::: {.sectionhead}
[Example Additional]{style="opacity:0.25"} Code [Summary]{style="opacity:0.25"}
:::

### A minimalist and elegant presentation theme

C++ code looks like this:

```{.cpp}
template<typename Space>
class Executor {
  std::unique_ptr<handle> exec_;

  template<typename Operation>
  void run(Operation Lambda);
}
```

Julia code looks like this:

```{.julia}
function sphere_vol(r)
    # julia allows Unicode names (in UTF-8 encoding)
    # so either "pi" or the symbol π can be used
    return 4/3*pi*r^3
end

vol = sphere_vol(3)
```

## Summary {#sec-summary}

::: {.sectionhead}
[Example Additional Code]{style="opacity:0.25"} Summary
:::

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presention
theme. Here are some options to get you started:

Add the theme to an existing project.

```{.bash}
quarto install extension pratikvn/quarto-revealjs-tum
```

... or, create a new project using this slide deck as a lean template.

```{.bash}
quarto use template pratik/quarto-revealjs-tum
```
